default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost # postgres
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV["DB_NAME"] %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
